baseURL = 'https://ahoydtu.de'
languageCode = 'en-us'
title = 'AhoyDTU'

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Getting started"
    url = "/getting_started/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3


[params]
  homeText = "Check how your Hoymiles inverter is performing"
